-- ============================================================
-- SCRIPT SQL PARA BASE DE DATOS SUPABASE (HAPPY VISION APP)
-- Copia y ejecuta este código en el SQL Editor de Supabase
-- ============================================================

-- 1. Tabla: usuarios
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'Optometrista',
    nombre TEXT NOT NULL,
    cargo TEXT,
    registro TEXT,
    telefono TEXT,
    sucursal TEXT DEFAULT 'Matriz',
    accesos JSONB DEFAULT '["Inicio", "Pacientes", "Generar Orden", "Trabajos", "Ventas", "Inventario", "Contabilidad", "Citas", "Asistente IA", "Usuarios", "Configuracion"]'::jsonb,
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla: sucursales
CREATE TABLE IF NOT EXISTS public.sucursales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    direccion TEXT,
    telefono TEXT,
    ciudad TEXT DEFAULT 'Quito',
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla: pacientes
CREATE TABLE IF NOT EXISTS public.pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion TEXT UNIQUE,
    nombre TEXT NOT NULL,
    nombres TEXT,
    apellidos TEXT,
    genero TEXT,
    direccion TEXT,
    edad TEXT,
    fecha_nacimiento DATE,
    telefono TEXT,
    correo TEXT,
    ocupacion TEXT,
    sucursal TEXT DEFAULT 'Matriz',
    notas TEXT,
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla: historias_clinicas
CREATE TABLE IF NOT EXISTS public.historias_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES public.pacientes(id) ON DELETE CASCADE,
    paciente_nombre TEXT,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    optometrista TEXT,
    motivo_consulta TEXT,
    ant_personales TEXT,
    ant_familiares TEXT,
    diabetes TEXT,
    hipertension TEXT,
    patologia_otra TEXT,
    observaciones TEXT,
    lenso_od TEXT,
    lenso_av_lej_od TEXT,
    lenso_av_cer_od TEXT,
    lenso_oi TEXT,
    lenso_av_lej_oi TEXT,
    lenso_av_cer_oi TEXT,
    rx_od TEXT,
    rx_av_lej_od TEXT,
    rx_av_cer_od TEXT,
    rx_oi TEXT,
    rx_av_lej_oi TEXT,
    rx_av_cer_oi TEXT,
    rx_od_esf TEXT,
    rx_od_cil TEXT,
    rx_od_eje TEXT,
    rx_od_add TEXT,
    rx_oi_esf TEXT,
    rx_oi_cil TEXT,
    rx_oi_eje TEXT,
    rx_oi_add TEXT,
    dp TEXT,
    tipo_lente TEXT,
    material TEXT,
    filtro TEXT,
    estado_muscular TEXT,
    seg_externo TEXT,
    test_colores TEXT,
    estado_refractivo TEXT,
    diagnostico TEXT,
    disposicion TEXT,
    recomendaciones TEXT,
    meses_proximo_control TEXT,
    necesita_lentes TEXT,
    sucursal TEXT DEFAULT 'Matriz',
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabla: historias_lc (Lentes de Contacto)
CREATE TABLE IF NOT EXISTS public.historias_lc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES public.pacientes(id) ON DELETE CASCADE,
    paciente_nombre TEXT,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    sucursal TEXT DEFAULT 'Matriz',
    optometrista TEXT,
    optometrista_login TEXT,
    lc_usuario_previo TEXT,
    lc_tipo_lente_ant TEXT,
    lc_marca_ant TEXT,
    lc_horas_uso TEXT,
    lc_solucion_habitual TEXT,
    lc_motivo_consulta TEXT,
    lc_avsc_od TEXT,
    lc_avsc_oi TEXT,
    lc_rx_od TEXT,
    lc_rx_oi TEXT,
    lc_distancia_vertice TEXT,
    lc_kera_od TEXT,
    lc_kera_oi TEXT,
    lc_astig_corneal_od TEXT,
    lc_astig_corneal_oi TEXT,
    lc_parpados TEXT,
    lc_conjuntiva TEXT,
    lc_eversion TEXT,
    lc_cornea TEXT,
    lc_but_od TEXT,
    lc_but_oi TEXT,
    lc_menisco TEXT,
    lc_prueba_tipo TEXT,
    lc_prueba_od TEXT,
    lc_prueba_oi TEXT,
    lc_centrado TEXT,
    lc_movimiento TEXT,
    lc_pushup TEXT,
    lc_rotacion TEXT,
    lc_sobre_od TEXT,
    lc_sobre_oi TEXT,
    lc_final_od TEXT,
    lc_final_oi TEXT,
    lc_marca_final TEXT,
    lc_modalidad TEXT,
    lc_regimen TEXT,
    lc_solucion_final TEXT,
    lc_insercion TEXT,
    lc_fecha_entrega TEXT,
    lc_proximo_control TEXT,
    lc_observaciones TEXT,
    recomendaciones TEXT,
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabla: inventario
CREATE TABLE IF NOT EXISTS public.inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT,
    producto TEXT,
    marca TEXT,
    modelo TEXT,
    color TEXT,
    categoria TEXT DEFAULT 'Armazones',
    cantidad_disponible INT DEFAULT 0,
    stock_minimo INT DEFAULT 2,
    precio_venta NUMERIC(10,2) DEFAULT 0.00,
    costo NUMERIC(10,2) DEFAULT 0.00,
    sucursal TEXT DEFAULT 'Matriz',
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabla: ordenes_trabajo
CREATE TABLE IF NOT EXISTS public.ordenes_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden TEXT,
    paciente_id BIGINT REFERENCES public.pacientes(id) ON DELETE SET NULL,
    paciente_nombre TEXT,
    fecha_orden TIMESTAMPTZ DEFAULT NOW(),
    fecha_entrega DATE,
    estado TEXT DEFAULT 'Pendiente',
    sucursal TEXT DEFAULT 'Matriz',
    armazon TEXT,
    luna TEXT,
    tratamiento TEXT,
    prescripcion JSONB,
    detalle_lentes TEXT,
    tipo_lente_laboratorio TEXT,
    distancia_pupilar TEXT,
    valor_total NUMERIC(10,2) DEFAULT 0.00,
    abono NUMERIC(10,2) DEFAULT 0.00,
    saldo NUMERIC(10,2) DEFAULT 0.00,
    metodo_pago TEXT,
    optometrista TEXT,
    usuario_creador TEXT,
    notas TEXT,
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabla: ventas
CREATE TABLE IF NOT EXISTS public.ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_factura TEXT,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    paciente_id BIGINT,
    cliente TEXT,
    total NUMERIC(10,2) DEFAULT 0.00,
    costo_total NUMERIC(10,2) DEFAULT 0.00,
    metodo_pago TEXT,
    detalles JSONB,
    sucursal TEXT DEFAULT 'Matriz',
    usuario TEXT,
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabla: gastos
CREATE TABLE IF NOT EXISTS public.gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT CURRENT_DATE,
    monto NUMERIC(10,2) DEFAULT 0.00,
    categoria TEXT,
    descripcion TEXT,
    usuario TEXT,
    sucursal TEXT DEFAULT 'Matriz',
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Tabla: caja_diaria
CREATE TABLE IF NOT EXISTS public.caja_diaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE DEFAULT CURRENT_DATE,
    monto_apertura NUMERIC(10,2) DEFAULT 0.00,
    monto_cierre NUMERIC(10,2) DEFAULT 0.00,
    abierta_por TEXT,
    cerrada_por TEXT,
    sucursal TEXT DEFAULT 'Matriz',
    estado TEXT DEFAULT 'Abierta',
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Tabla: citas
CREATE TABLE IF NOT EXISTS public.citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES public.pacientes(id) ON DELETE SET NULL,
    paciente_nombre TEXT,
    fecha_cita DATE NOT NULL,
    hora_cita TIME NOT NULL,
    optometrista TEXT,
    motivo TEXT,
    estado TEXT DEFAULT 'Confirmada',
    sucursal TEXT DEFAULT 'Matriz',
    creado_el TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Tabla: auditoria
CREATE TABLE IF NOT EXISTS public.auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMPTZ DEFAULT NOW(),
    usuario TEXT,
    nombre_usuario TEXT,
    accion TEXT,
    entidad TEXT,
    detalle TEXT,
    sucursal TEXT DEFAULT 'Matriz'
);

-- DATOS INICIALES POR DEFECTO
INSERT INTO public.sucursales (nombre, direccion, ciudad) 
VALUES ('Matriz', 'Av. Principal', 'Quito')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.usuarios (username, password, role, nombre, sucursal, accesos)
VALUES ('admin', 'admin123', 'Administrador', 'Administrador Sistema', 'Matriz', '["Inicio", "Pacientes", "Generar Orden", "Trabajos", "Ventas", "Inventario", "Contabilidad", "Citas", "Asistente IA", "Usuarios", "Configuracion"]'::jsonb)
ON CONFLICT (username) DO NOTHING;
